### ISSUE TITLE
issues with the code

### ISSUE THREAD

**Issue by bartwalczak1** [tinrab/go-elasticsearch-example#2]
missing type:
```
res := SearchResponse{
  Time: fmt.Sprintf("%d", result.TookInMillis),
  Hits: fmt.Sprintf("%d", result.Hits.TotalHits),
}
 ```

```
docs := make([]DocumentResponse, 0) 
``` 
<- missing struct

```
res.Documents = docs
```
 <- undefined res 

I was following instructions on the website, without looking at the source code on github. Please update your instructions and add missing code there

**Comment by tinrab** [comment]
Code snippets in the article are intentionally incomplete.

**Comment by bartwalczak1** [comment]
ok well, I guess best practice would be to note it down somewhere in the tutorial. anyways thanks for a quick turnaround!
